### ISSUE TITLE
Invalid Date when you access a bus line at a time that is out of it's schedule

### ISSUE THREAD

**Issue by radufarcas10** [Utwo/bus-pwa#2]
Hi,

I like your PWA and I'm using it  a few times a week so I thought you might be interested in a few bugs I've encountered using it.
First, if I have a favorite line and I'm opening the app to check it's schedule at a time that isn't in that line's schedule, it shows some Invalid Date - Almost NaN error.
![screenshot_20180208-225800](https://user-images.githubusercontent.com/17551199/35998385-185762c6-0d25-11e8-9081-a229a3617631.png)

And second, if I refresh the favorites page, it doesn't load the CSS anymore
![screenshot_20180208-225839](https://user-images.githubusercontent.com/17551199/35998399-23f3b210-0d25-11e8-9ef6-3193d9a23371.png)

All of these are happening inside the PWA.

Keep up the good work!

**Comment by Utwo** [comment]
I think the second issue is resolved now. Let me know if it's ok :)

**Comment by Utwo** [comment]
Everything should work now! Thank you for report!
